import xml.etree.ElementTree as ET

label_dic = {
    '1': 'CONTROLLER',
    '1.1': 'CONTROLLER.IDENTITY',
    '1.1.1': 'CONTROLLER.IDENTITY.REGISTER_NUMBER',

    '1.2': 'CONTROLLER.CONTACT',
    '1.2.1': 'CONTROLLER.CONTACT.PHONE_NUMBER',
    '1.2.2': 'CONTROLLER.CONTACT.E-MAIL',
    '1.2.3': 'CONTROLLER.CONTACT.LEGAL_ADDRESS',

    '2': 'CONTROLLER_REPRESENTATIVE',
    '2.1': 'CONTROLLER_REPRESENTATIVE.IDENTITY',
    '2.1.1': 'CONTROLLER_REPRESENTATIVE.REGISTER_NUMBER',

    '2.2': 'CONTROLLER_REPRESENTATIVE.CONTACT',
    '2.2.1': 'CONTROLLER_REPRESENTATIVE.CONTACT.PHONE_NUMBER',
    '2.2.2': 'CONTROLLER_REPRESENTATIVE.CONTACT.E-MAIL',
    '2.2.3': 'CONTROLLER_REPRESENTATIVE.CONTACT.LEGAL_ADDRESS',

    '3': 'DPO',
    '3.1': 'DPO.IDENTITY',
    '3.1.1': 'DPO.IDENTITY.REGISTER_NUMBER',

    '3.2': 'DPO.CONTACT',
    '3.2.1': 'DPO.CONTACT.PHONE_NUMBER',
    '3.2.2': 'DPO.CONTACT.E-MAIL',
    '3.2.3': 'DPO.CONTACT.LEGAL_ADDRESS',

    '4': 'DATA_SUBJECT_RIGHT',
    '4.1': 'DATA_SUBJECT_RIGHT.INFORMATION',
    '4.1.1': 'DATA_SUBJECT_RIGHT.INFORMATION.POLICY_CHANGE',
    '4.1.2': 'DATA_SUBJECT_RIGHT.INFORMATION.DATA_BREACH_NOTIFICATION',
    '4.1.3': 'DATA_SUBJECT_RIGHT.INFORMATION.OTHERS',
    '4.2': 'DATA_SUBJECT_RIGHT.ACCESS',
    '4.3': 'DATA_SUBJECT_RIGHT.RECTIFICATION',
    '4.4': 'DATA_SUBJECT_RIGHT.RESTRICTION',
    '4.5': 'DATA_SUBJECT_RIGHT.ERASURE',
    '4.6': 'DATA_SUBJECT_RIGHT.OBJECT',
    '4.7': 'DATA_SUBJECT_RIGHT.PORTABILITY',
    '4.8': 'DATA_SUBJECT_RIGHT.AUTO_DECISION_MAKING',
    '4.9': 'DATA_SUBJECT_RIGHT.WITHDRAW_CONSENT',

    '5': 'DP_PRINCIPLE',
    '5.1': 'DP_PRINCIPLE.PURPOSE_LIMITATION',
    '5.2': 'DP_PRINCIPLE.DATA_MINIMIZATION',
    '6': 'USER_CHOICE',

    '7': 'COMPLAINT',
    '7.1': 'COMPLAINT.SA',

    '8': 'PD_CATEGORY',
    '8.1': 'PD_CATEGORY.TYPE',
    '8.1.1': 'PD_CATEGORY.TYPE.THIRD-PARTY',
    '8.1.2': 'PD_CATEGORY.TYPE.PUBLICLY',

    '8.2': 'PD_CATEGORY.SPECIAL',
    '8.2.1': 'PD_CATEGORY.SPECIAL.CONDITION',

    '9': 'PD_ORIGIN',
    '9.1': 'PD_ORIGIN.DIRECT_ACTIVE',
    '9.2': 'PD_ORIGIN.DIRECT_PASSIVE',
    '9.2.1': 'PD_ORIGIN.DIRECT_PASSIVE.COOKIE',
    '9.3': 'PD_ORIGIN.INDIRECT',
    '9.3.1': 'PD_ORIGIN.INDIRECT.THIRD-PARTY',
    '9.3.2': 'PD_ORIGIN.INDIRECT.PUBLICLY',

    '10': 'LAWFUL_BASIS',
    '10.1': 'LAWFUL_BASIS.CONTRACT',
    '10.1.1': 'LAWFUL_BASIS.CONTRACT.CONTRACTUAL',
    '10.1.2': 'LAWFUL_BASIS.CONTRACT.TO_ENTER_CONTRACT',
    '10.1.3': 'LAWFUL_BASIS.CONTRACT.STATUTORY',

    '10.2': 'LAWFUL_BASIS.PUBLIC_FUNCTION',
    '10.3': 'LAWFUL_BASIS.LEGITIMATE_INTEREST',
    '10.4': 'LAWFUL_BASIS.VITAL_INTEREST',
    '10.5': 'LAWFUL_BASIS.CONSENT',
    '10.6': 'LAWFUL_BASIS.LEGAL_OBLIGATION',

    '11': 'PROCESSING_PURPOSES',
    '12': 'PD_SECURITY',
    '13': 'PD_PROVISION_OBLIGED',

    '14': 'TRANSFER_OUTSIDE_EUROPE',
    '14.1': 'TRANSFER_OUTSIDE_EUROPE.SPECIFIC_DEROGATION',
    '14.1.1': 'TRANSFER_OUTSIDE_EUROPE.SPECIFIC_DEROGATION.UNAMBIGUOUS_CONSENT',
    '14.1.2': 'TRANSFER_OUTSIDE_EUROPE.SPECIFIC_DEROGATION.CONTRACT',
    '14.1.3': 'TRANSFER_OUTSIDE_EUROPE.SPECIFIC_DEROGATION.PUBLIC_INTEREST',
    '14.1.4': 'TRANSFER_OUTSIDE_EUROPE.SPECIFIC_DEROGATION.LEGAL_CLAIMS',
    '14.1.5': 'TRANSFER_OUTSIDE_EUROPE.SPECIFIC_DEROGATION.VITAL_INTEREST',
    '14.1.6': 'TRANSFER_OUTSIDE_EUROPE.SPECIFIC_DEROGATION.LEGITIMATE_INTEREST',

    '14.2': 'TRANSFER_OUTSIDE_EUROPE.SAFEGUARDS',
    '14.2.1': 'TRANSFER_OUTSIDE_EUROPE.SAFEGUARDS.LEGAL_INSTRUMENT',
    '14.2.2': 'TRANSFER_OUTSIDE_EUROPE.SAFEGUARDS.BINDING_CORPORATE',
    '14.2.3': 'TRANSFER_OUTSIDE_EUROPE.SAFEGUARDS.EU_MODEL_CLAUSES',
    '14.2.4': 'TRANSFER_OUTSIDE_EUROPE.SAFEGUARDS.CODE_OF_CONDUCT',
    '14.2.5': 'TRANSFER_OUTSIDE_EUROPE.SAFEGUARDS.CERTIFICATION_MECHANISM',

    '14.3': 'TRANSFER_OUTSIDE_EUROPE.ADEQUACY_DECISION',
    '14.3.1': 'TRANSFER_OUTSIDE_EUROPE.ADEQUACY_DECISION.TERRITORY',
    '14.3.2': 'TRANSFER_OUTSIDE_EUROPE.ADEQUACY_DECISION.SECTOR',
    '14.3.3': 'TRANSFER_OUTSIDE_EUROPE.ADEQUACY_DECISION.COUNTRY',

    '15': 'CHILDREN',

    '16': 'PD_STORAGE_DETAILS',
    '16.1': 'PD_STORAGE_DETAILS.TIME',
    '16.2': 'PD_STORAGE_DETAILS.LOCATION',
    '16.3': 'PD_STORAGE_DETAILS.DISPOSAL_METHOD',

    '17': 'DATA_SHARING',
    '17.1': 'DATA_SHARING.RECIPIENT',
    '17.2': 'DATA_SHARING.CONDITION',

    '18': 'NON-GDPR',
    '18.1': 'NON-GDPR.COOKIE',
    '18.2': 'NON-GDPR.OTHER_LEGISLATION',

    '19': 'UNKNOWN'
}

label_dic2 = {k:v for v, k in label_dic.items()}


